---
- name: Create the student user with no password and restricted permissions
  hosts: local  # Uses the inventory file
  become: true
  tasks:

    - name: Ensure the student group exists
      ansible.builtin.group:
        name: student
        state: present

    - name: Ensure the student user exists with no password
      ansible.builtin.user:
        name: student
        shell: /bin/bash
        home: /home/student
        create_home: yes
        groups: student
        append: no
        password_lock: true  # Ensures no password is set

    - name: Ensure student home directory permissions are correct
      ansible.builtin.file:
        path: /home/student
        owner: student
        group: student
        mode: "0700"

    - name: Prevent student from using sudo
      ansible.builtin.file:
        path: /etc/sudoers.d/student
        state: absent

    - name: Set a default wallpaper
      ansible.builtin.copy:
        src: /usr/share/backgrounds/default.jpg
        dest: /home/student/.background.jpg
        owner: student
        group: student
        mode: "0644"

    - name: Apply dconf settings
      ansible.builtin.command: dconf update

    - name: Enable auto-login for student (Cinnamon with LightDM)
      ansible.builtin.blockinfile:
        path: /etc/lightdm/lightdm.conf
        create: yes
        block: |
          [Seat:*]
          autologin-user=student
          autologin-user-timeout=0
      notify: Restart LightDM

  handlers:
    - name: Restart LightDM
      ansible.builtin.command: systemctl restart lightdm
      ignore_errors: yes